version: '3'
services:
  goose:
    build: .
    volumes:
      - ./:/node_app
      - node_modules_cache:/node_app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

volumes:
  node_modules_cache: